#!/usr/bin/env bash
# Concatenates every migration into supabase/setup.sql so a new project can be
# set up with one paste into the Supabase SQL Editor.
#   npm run db:bundle
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/setup.sql"
{
  echo "-- GENERATED by scripts/bundle-setup-sql.sh from supabase/migrations. Do not edit."
  echo "-- Paste into Supabase > SQL Editor > New query, then Run. Run it once, on a new project."
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo
    echo "-- ===================================================================="
    echo "-- $(basename "$f")"
    echo "-- ===================================================================="
    cat "$f"
  done
} > "$OUT"
echo "Wrote $OUT"
