/**
 * Every metric the portal knows about. This is the single source of truth for
 * display names, tooltip definitions, formatting, and how each metric rolls up
 * over a date range. Parsers, connectors, and the dashboard all reference
 * metrics by these keys.
 *
 * Copy rule: definitions are client-facing. Plain language, no em dashes.
 */
import type { Aggregation, MetricDefinition } from "./types";

const sum: Aggregation = { type: "sum" };
const last: Aggregation = { type: "last" };
const unique: Aggregation = { type: "unique" };
const ratio = (numerator: string, denominator: string): Aggregation => ({
  type: "ratio",
  numerator,
  denominator,
});

const definitions: MetricDefinition[] = [
  // -------------------------------------------------------------------------
  // Website (GA4)
  // -------------------------------------------------------------------------
  {
    key: "ga4_sessions",
    source: "ga4",
    label: "Sessions",
    definition: "The number of visits to your website. One person can visit more than once.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_engaged_sessions",
    source: "ga4",
    label: "Engaged Sessions",
    definition:
      "Visits where the person stayed at least 10 seconds, viewed more than one page, or completed a key action.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_engagement_rate",
    source: "ga4",
    label: "Engagement Rate",
    definition:
      "The share of website visits that were engaged. A high rate means visitors are finding what they came for.",
    format: "percent",
    aggregation: ratio("ga4_engaged_sessions", "ga4_sessions"),
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
    glossaryTerm: "engagement_rate",
  },
  {
    key: "ga4_key_events",
    source: "ga4",
    label: "Key Events",
    definition:
      "Important actions taken on your website, like submitting a form, calling, or booking. These are the visits most likely to become customers.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_users",
    source: "ga4",
    label: "Visitors",
    definition: "The number of different people who visited your website.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_page_views",
    source: "ga4",
    label: "Page Views",
    definition: "The total number of pages viewed on your website.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["landing_page"],
  },

  {
    key: "ga4_engagement_minutes",
    source: "ga4",
    label: "Engagement Time",
    definition: "Total time people actively spent on your website, with the page open and in view.",
    format: "duration",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_avg_engagement_time",
    source: "ga4",
    label: "Avg. Time on Site",
    definition: "How long the average visit actively spent on your website. Longer means people are reading and exploring, not leaving right away.",
    format: "duration",
    aggregation: ratio("ga4_engagement_minutes", "ga4_sessions"),
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_revenue",
    source: "ga4",
    label: "Online Sales",
    definition: "Money from orders placed on your website, as tracked by Google Analytics.",
    format: "currency",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_transactions",
    source: "ga4",
    label: "Online Orders",
    definition: "The number of orders placed on your website.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_aov",
    source: "ga4",
    label: "Avg. Order Value",
    definition: "The average amount spent per online order.",
    format: "currency",
    aggregation: ratio("ga4_revenue", "ga4_transactions"),
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },
  {
    key: "ga4_purchase_rate",
    source: "ga4",
    label: "Order Rate",
    definition: "The share of website visits that ended in an order.",
    format: "percent",
    aggregation: ratio("ga4_transactions", "ga4_sessions"),
    upIsGood: true,
    dimensions: ["channel", "landing_page"],
  },

  // -------------------------------------------------------------------------
  // Facebook
  // -------------------------------------------------------------------------
  {
    key: "fb_followers",
    source: "meta_facebook",
    label: "Followers",
    definition: "People who follow your Facebook Page and can see your updates in their feed.",
    format: "number",
    aggregation: last,
    upIsGood: true,
    glossaryTerm: "followers",
  },
  {
    key: "fb_net_new_followers",
    source: "meta_facebook",
    label: "Net New Followers",
    definition: "New Facebook followers gained, minus people who unfollowed.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "net_new_followers",
  },
  {
    key: "fb_views",
    source: "meta_facebook",
    label: "Views",
    definition: "The number of times your Facebook Page and posts were seen.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "fb_reach",
    source: "meta_facebook",
    label: "Reach",
    definition: "The number of different people who saw your Facebook content.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "fb_interactions",
    source: "meta_facebook",
    label: "Engagements",
    definition: "Reactions, comments, shares, and clicks on your Facebook content.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "content_interactions",
  },
  {
    key: "fb_reactions",
    source: "meta_facebook",
    label: "Reactions",
    definition: "Likes, loves, and other reactions on your Facebook posts.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "fb_page_visits",
    source: "meta_facebook",
    label: "Page Visits",
    definition: "The number of times people opened your Facebook Page.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "profile_visits",
  },
  {
    key: "fb_engagement_rate",
    source: "meta_facebook",
    label: "Engagement Rate",
    definition: "Engagements as a share of views on Facebook.",
    format: "percent",
    aggregation: ratio("fb_interactions", "fb_views"),
    upIsGood: true,
    glossaryTerm: "engagement_rate",
  },
  {
    key: "fb_3s_views",
    source: "meta_facebook",
    label: "3-Second Views",
    definition: "The number of times your Facebook videos were watched for at least 3 seconds.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "fb_1min_views",
    source: "meta_facebook",
    label: "1-Minute Views",
    definition: "The number of times your Facebook videos were watched for at least 1 minute.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "fb_watch_time",
    source: "meta_facebook",
    label: "Watch Time",
    definition: "The total time people spent watching your Facebook videos.",
    format: "duration",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "fb_reels_views",
    source: "meta_facebook",
    label: "Reels Views",
    definition: "The number of times your Facebook Reels were watched.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "fb_reels_interactions",
    source: "meta_facebook",
    label: "Reels Engagements",
    definition: "Reactions, comments, and shares on your Facebook Reels.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },

  {
    key: "fb_reels_engagement_share",
    source: "meta_facebook",
    label: "Reels Engagement Share",
    definition: "The share of all your Facebook engagement that came from Reels.",
    format: "percent",
    aggregation: ratio("fb_reels_interactions", "fb_interactions"),
    upIsGood: true,
  },

  // -------------------------------------------------------------------------
  // Instagram
  // -------------------------------------------------------------------------
  {
    key: "ig_followers",
    source: "meta_instagram",
    label: "Followers",
    definition: "People who follow your Instagram account.",
    format: "number",
    aggregation: last,
    upIsGood: true,
    glossaryTerm: "followers",
  },
  {
    key: "ig_net_new_followers",
    source: "meta_instagram",
    label: "Net New Followers",
    definition: "New Instagram followers gained, minus people who unfollowed.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "net_new_followers",
  },
  {
    key: "ig_views",
    source: "meta_instagram",
    label: "Views",
    definition: "The number of times your Instagram posts, Reels, and stories were seen.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "ig_reach",
    source: "meta_instagram",
    label: "Reach",
    definition: "The number of different people who saw your Instagram content.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "ig_interactions",
    source: "meta_instagram",
    label: "Interactions",
    definition: "Likes, comments, shares, and saves on your Instagram content.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "content_interactions",
  },
  {
    key: "ig_profile_visits",
    source: "meta_instagram",
    label: "Profile Visits",
    definition: "The number of times people opened your Instagram profile.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "profile_visits",
  },
  {
    key: "ig_engagement_rate",
    source: "meta_instagram",
    label: "Engagement Rate",
    definition: "Interactions as a share of views on Instagram.",
    format: "percent",
    aggregation: ratio("ig_interactions", "ig_views"),
    upIsGood: true,
    glossaryTerm: "engagement_rate",
  },
  {
    key: "ig_reels_views",
    source: "meta_instagram",
    label: "Reels Views",
    definition: "The number of times your Instagram Reels were watched.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_reels_interactions",
    source: "meta_instagram",
    label: "Reels Interactions",
    definition: "Likes, comments, shares, and saves on your Instagram Reels.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_viewers",
    source: "meta_instagram",
    label: "Viewers",
    definition: "The number of different accounts that viewed your Instagram content. Each account counts once, however many times it viewed.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
  },
  {
    key: "ig_story_views",
    source: "meta_instagram",
    label: "Story Views",
    definition: "The number of times your Instagram Stories were seen.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_live_views",
    source: "meta_instagram",
    label: "Live Video Views",
    definition: "The number of times your Instagram live videos were watched.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_post_interactions",
    source: "meta_instagram",
    label: "Post Interactions",
    definition: "Likes, comments, shares, and saves on your Instagram photo and carousel posts.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_story_interactions",
    source: "meta_instagram",
    label: "Story Interactions",
    definition: "Replies, shares, and reactions on your Instagram Stories.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_live_interactions",
    source: "meta_instagram",
    label: "Live Video Interactions",
    definition: "Comments, shares, and reactions on your Instagram live videos.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_bio_link_taps",
    source: "meta_instagram",
    label: "Bio Link Taps",
    definition: "The number of times people tapped the link in your Instagram bio.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_address_taps",
    source: "meta_instagram",
    label: "Business Address Taps",
    definition: "The number of times people tapped your business address on Instagram.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ig_post_views",
    source: "meta_instagram",
    label: "Post Views",
    definition: "The number of times your Instagram photo and carousel posts were seen.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },

  // -------------------------------------------------------------------------
  // Google Ads (stored as metrics by campaign; rates recomputed from parts)
  // -------------------------------------------------------------------------
  {
    key: "gads_spend",
    source: "google_ads",
    label: "Cost",
    definition: "Total spent on Google Ads in the period.",
    format: "currency",
    aggregation: sum,
    upIsGood: false,
    dimensions: ["campaign", "search_term", "keyword", "ad_group"],
  },
  {
    key: "gads_impressions",
    source: "google_ads",
    label: "Impressions",
    definition: "The number of times your Google ads were shown.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["campaign", "search_term", "keyword", "ad_group"],
  },
  {
    key: "gads_clicks",
    source: "google_ads",
    label: "Clicks",
    definition: "The number of times people clicked your Google ads.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["campaign", "search_term", "keyword", "ad_group"],
  },
  {
    key: "gads_conversions",
    source: "google_ads",
    label: "Conversions",
    definition: "Actions you count as valuable that came from your Google ads, such as calls, form fills, or purchases.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["campaign", "search_term", "keyword", "ad_group"],
  },
  {
    key: "gads_conversion_value",
    source: "google_ads",
    label: "Conversion Value",
    definition: "The total value of the conversions from your Google ads.",
    format: "currency",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["campaign", "search_term", "keyword", "ad_group"],
  },
  {
    key: "gads_ctr",
    source: "google_ads",
    label: "Click-Through Rate",
    definition: "The share of people who clicked your Google ad after seeing it.",
    format: "percent",
    aggregation: ratio("gads_clicks", "gads_impressions"),
    upIsGood: true,
  },
  {
    key: "gads_cpc",
    source: "google_ads",
    label: "Avg. Cost per Click",
    definition: "The average cost of each click on your Google ads.",
    format: "currency",
    aggregation: ratio("gads_spend", "gads_clicks"),
    upIsGood: false,
  },
  {
    key: "gads_cpa",
    source: "google_ads",
    label: "Cost per Conversion",
    definition: "The average cost of each conversion from your Google ads.",
    format: "currency",
    aggregation: ratio("gads_spend", "gads_conversions"),
    upIsGood: false,
  },
  {
    key: "gads_conversion_rate",
    source: "google_ads",
    label: "Conversion Rate",
    definition: "The share of clicks on your Google ads that led to a conversion.",
    format: "percent",
    aggregation: ratio("gads_conversions", "gads_clicks"),
    upIsGood: true,
  },
  {
    key: "gads_roas",
    source: "google_ads",
    label: "Return on Ad Spend",
    definition: "Conversion value for every dollar spent on Google Ads.",
    format: "multiplier",
    aggregation: ratio("gads_conversion_value", "gads_spend"),
    upIsGood: true,
  },

  // -------------------------------------------------------------------------
  // Google Search (Search Console): organic results, not ads
  // -------------------------------------------------------------------------
  {
    key: "gsc_clicks",
    source: "search_console",
    label: "Search Clicks",
    definition: "Times people clicked through to your website from a regular (unpaid) Google search result.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["query", "page"],
  },
  {
    key: "gsc_impressions",
    source: "search_console",
    label: "Search Impressions",
    definition: "Times your website appeared in Google search results, whether or not anyone clicked.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["query", "page"],
  },
  {
    key: "gsc_position_weighted",
    source: "search_console",
    label: "Position x Impressions",
    definition: "Used to work out average position over any date range.",
    format: "number",
    aggregation: sum,
    upIsGood: false,
    dimensions: ["query", "page"],
    internal: true,
  },
  {
    key: "gsc_ctr",
    source: "search_console",
    label: "Search Click Rate",
    definition: "The share of people who clicked your website after seeing it in Google search results.",
    format: "percent",
    aggregation: ratio("gsc_clicks", "gsc_impressions"),
    upIsGood: true,
    dimensions: ["query", "page"],
  },
  {
    key: "gsc_position",
    source: "search_console",
    label: "Avg. Google Position",
    definition: "Where your website ranks in Google results on average. 1 is the top result; 1 to 10 is the first page. Lower is better.",
    format: "number",
    aggregation: ratio("gsc_position_weighted", "gsc_impressions"),
    upIsGood: false,
    dimensions: ["query", "page"],
  },

  // -------------------------------------------------------------------------
  // Meta Ads (rolled up from ad_metrics_daily; reach from metrics_period)
  // -------------------------------------------------------------------------
  {
    key: "ads_leads",
    source: "meta_ads",
    label: "Leads",
    definition: "People who filled out your lead form after seeing your ad.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ads_spend",
    source: "meta_ads",
    label: "Amount Spent",
    definition: "The total amount spent on your ads.",
    format: "currency",
    aggregation: sum,
    upIsGood: false,
  },
  {
    key: "ads_reach",
    source: "meta_ads",
    label: "Reach",
    definition: "The number of different people who saw your ads at least once.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
  },
  {
    key: "ads_impressions",
    source: "meta_ads",
    label: "Impressions",
    definition: "The total number of times your ads were shown.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ads_clicks",
    source: "meta_ads",
    label: "Clicks",
    definition: "The number of times people clicked your ads.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "ads_frequency",
    source: "meta_ads",
    label: "Frequency",
    definition: "How many times, on average, each person saw your ads.",
    format: "multiplier",
    aggregation: ratio("ads_impressions", "ads_reach"),
    upIsGood: true,
  },
  {
    key: "ads_ctr",
    source: "meta_ads",
    label: "Click-Through Rate",
    definition: "The share of ad views that led to a click.",
    format: "percent",
    aggregation: ratio("ads_clicks", "ads_impressions"),
    upIsGood: true,
  },
  {
    key: "ads_cpl",
    source: "meta_ads",
    label: "Cost Per Lead",
    definition: "The average cost for each lead your ads generated.",
    format: "currency",
    aggregation: ratio("ads_spend", "ads_leads"),
    upIsGood: false,
  },
  {
    key: "ads_cpc",
    source: "meta_ads",
    label: "Cost Per Click",
    definition: "The average cost for each click on your ads.",
    format: "currency",
    aggregation: ratio("ads_spend", "ads_clicks"),
    upIsGood: false,
  },

  // -------------------------------------------------------------------------
  // Shopify
  // -------------------------------------------------------------------------
  {
    key: "shop_total_sales",
    source: "shopify",
    label: "Total Sales",
    definition: "Revenue from orders, after discounts and returns.",
    format: "currency",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "product"],
  },
  {
    key: "shop_orders",
    source: "shopify",
    label: "Orders",
    definition: "The number of orders placed in your store.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    dimensions: ["channel", "product"],
  },
  {
    key: "shop_aov",
    source: "shopify",
    label: "Average Order Value",
    definition: "How much a customer spends per order on average.",
    format: "currency",
    aggregation: ratio("shop_total_sales", "shop_orders"),
    upIsGood: true,
    dimensions: ["channel"],
  },
  {
    key: "shop_sessions",
    source: "shopify",
    label: "Store Sessions",
    definition: "The number of visits to your online store.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "shop_conversion_rate",
    source: "shopify",
    label: "Conversion Rate",
    definition: "The share of store visits that ended in an order.",
    format: "percent",
    aggregation: ratio("shop_orders", "shop_sessions"),
    upIsGood: true,
  },
  {
    key: "shop_customers",
    source: "shopify",
    label: "Customers",
    definition: "The number of different customers who placed an order.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
  },
  {
    key: "shop_returning_customers",
    source: "shopify",
    label: "Returning Customers",
    definition: "Customers who had ordered from you before.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
  },
  {
    key: "shop_returning_customer_rate",
    source: "shopify",
    label: "Returning Customer Rate",
    definition: "The share of customers who had ordered from you before.",
    format: "percent",
    aggregation: ratio("shop_returning_customers", "shop_customers"),
    upIsGood: true,
  },

  // -------------------------------------------------------------------------
  // TikTok
  // -------------------------------------------------------------------------
  {
    key: "tt_followers",
    source: "tiktok",
    label: "Followers",
    definition: "People who follow your TikTok account.",
    format: "number",
    aggregation: last,
    upIsGood: true,
    glossaryTerm: "followers",
  },
  {
    key: "tt_net_new_followers",
    source: "tiktok",
    label: "Net New Followers",
    definition: "New TikTok followers gained, minus people who unfollowed.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "net_new_followers",
  },
  {
    key: "tt_views",
    source: "tiktok",
    label: "Video Views",
    definition: "The number of times your TikTok videos were watched.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "tt_interactions",
    source: "tiktok",
    label: "Interactions",
    definition: "Likes, comments, and shares on your TikTok videos.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "content_interactions",
  },
  {
    key: "tt_profile_views",
    source: "tiktok",
    label: "Profile Views",
    definition: "The number of times people opened your TikTok profile.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "profile_visits",
  },
  {
    key: "tt_engagement_rate",
    source: "tiktok",
    label: "Engagement Rate",
    definition: "Interactions as a share of video views on TikTok.",
    format: "percent",
    aggregation: ratio("tt_interactions", "tt_views"),
    upIsGood: true,
    glossaryTerm: "engagement_rate",
  },

  // -------------------------------------------------------------------------
  // LinkedIn
  // -------------------------------------------------------------------------
  {
    key: "li_followers",
    source: "linkedin",
    label: "Followers",
    definition: "People who follow your LinkedIn company page.",
    format: "number",
    aggregation: last,
    upIsGood: true,
    glossaryTerm: "followers",
  },
  {
    key: "li_net_new_followers",
    source: "linkedin",
    label: "Net New Followers",
    definition: "New LinkedIn followers gained, minus people who unfollowed.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "net_new_followers",
  },
  {
    key: "li_impressions",
    source: "linkedin",
    label: "Impressions",
    definition: "The number of times your LinkedIn posts were seen.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "li_interactions",
    source: "linkedin",
    label: "Interactions",
    definition: "Reactions, comments, reposts, and clicks on your LinkedIn posts.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "content_interactions",
  },
  {
    key: "li_page_views",
    source: "linkedin",
    label: "Page Views",
    definition: "The number of times people opened your LinkedIn company page.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
    glossaryTerm: "profile_visits",
  },
  {
    key: "li_unique_visitors",
    source: "linkedin",
    label: "Unique Visitors",
    definition: "The number of different people who visited your LinkedIn page.",
    format: "number",
    aggregation: unique,
    upIsGood: true,
  },
  {
    key: "li_button_clicks",
    source: "linkedin",
    label: "Custom Button Clicks",
    definition: "The number of times people clicked the custom button on your LinkedIn page.",
    format: "number",
    aggregation: sum,
    upIsGood: true,
  },
  {
    key: "li_comp_followers",
    source: "linkedin",
    label: "Total Followers",
    definition: "Total LinkedIn followers for each page in your competitor comparison.",
    format: "number",
    // A reading for the period LinkedIn shows (e.g. last 30 days), by company.
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_followers_change",
    source: "linkedin",
    label: "Total Followers Change",
    definition: "The change LinkedIn shows for total followers against the previous period.",
    format: "percent",
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_new_followers",
    source: "linkedin",
    label: "New Followers",
    definition: "New LinkedIn followers each page in your competitor comparison gained in the period.",
    format: "number",
    // A reading for the period LinkedIn shows (e.g. last 30 days), by company.
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_new_followers_change",
    source: "linkedin",
    label: "New Followers Change",
    definition: "The change LinkedIn shows for new followers against the previous period.",
    format: "percent",
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_posts",
    source: "linkedin",
    label: "Posts",
    definition: "LinkedIn posts each page in your competitor comparison published in the period.",
    format: "number",
    // A reading for the period LinkedIn shows (e.g. last 30 days), by company.
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_posts_change",
    source: "linkedin",
    label: "Posts Change",
    definition: "The change LinkedIn shows for posts against the previous period.",
    format: "percent",
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_engagements",
    source: "linkedin",
    label: "Engagements",
    definition: "Reactions, comments, and reposts on each competitor page's LinkedIn posts in the period.",
    format: "number",
    // A reading for the period LinkedIn shows (e.g. last 30 days), by company.
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_comp_engagements_change",
    source: "linkedin",
    label: "Engagements Change",
    definition: "The change LinkedIn shows for engagements against the previous period.",
    format: "percent",
    aggregation: last,
    upIsGood: true,
    dimensions: ["competitor", "own_page"],
  },
  {
    key: "li_engagement_rate",
    source: "linkedin",
    label: "Engagement Rate",
    definition: "Interactions as a share of impressions on LinkedIn.",
    format: "percent",
    aggregation: ratio("li_interactions", "li_impressions"),
    upIsGood: true,
    glossaryTerm: "engagement_rate",
  },

  // -------------------------------------------------------------------------
  // Combined (executive summary hero tiles)
  // -------------------------------------------------------------------------
  {
    key: "total_audience_reach",
    source: "combined",
    label: "Total Audience Reach",
    definition: "Views on Facebook, Instagram, and TikTok combined. LinkedIn reports Impressions, a different measure, so it is shown separately.",
    format: "number",
    // LinkedIn Impressions are a different measure, so they are not added in.
    aggregation: { type: "derived_sum", of: ["fb_views", "ig_views", "tt_views"] },
    upIsGood: true,
    glossaryTerm: "reach_views",
  },
  {
    key: "total_interactions",
    source: "combined",
    label: "Total Interactions",
    definition: "Likes, comments, shares, saves, and clicks across all of your social media platforms.",
    format: "number",
    aggregation: {
      type: "derived_sum",
      of: ["fb_interactions", "ig_interactions", "tt_interactions", "li_interactions"],
    },
    upIsGood: true,
    glossaryTerm: "content_interactions",
  },
  {
    key: "total_followers",
    source: "combined",
    label: "Total Audience",
    definition: "Followers across all of your social media platforms combined.",
    format: "number",
    aggregation: { type: "derived_sum", of: ["fb_followers", "ig_followers", "tt_followers", "li_followers"] },
    upIsGood: true,
    glossaryTerm: "followers",
  },
  {
    key: "total_net_new_followers",
    source: "combined",
    label: "Net New Followers",
    definition: "New followers gained across all platforms, minus people who unfollowed.",
    format: "number",
    aggregation: {
      type: "derived_sum",
      of: ["fb_net_new_followers", "ig_net_new_followers", "tt_net_new_followers", "li_net_new_followers"],
    },
    upIsGood: true,
    glossaryTerm: "net_new_followers",
  },
];

export const METRICS: Readonly<Record<string, MetricDefinition>> = Object.freeze(
  Object.fromEntries(definitions.map((d) => [d.key, d])),
);

export function getMetric(key: string): MetricDefinition {
  const def = METRICS[key];
  if (!def) throw new Error(`Unknown metric key: ${key}`);
  return def;
}

/** Net follower changes and percent changes (LinkedIn competitors) can be below zero. */
export function canBeNegative(key: string): boolean {
  return key.endsWith("_net_new_followers") || key.endsWith("_change");
}

export function isMetricKey(key: string): boolean {
  return key in METRICS;
}

/** Per-platform keys used by the Social Media Overview table. */
export const SOCIAL_OVERVIEW_KEYS = {
  meta_facebook: { followers: "fb_followers", netNew: "fb_net_new_followers", views: "fb_views", interactions: "fb_interactions" },
  meta_instagram: { followers: "ig_followers", netNew: "ig_net_new_followers", views: "ig_views", interactions: "ig_interactions" },
  tiktok: { followers: "tt_followers", netNew: "tt_net_new_followers", views: "tt_views", interactions: "tt_interactions" },
  linkedin: { followers: "li_followers", netNew: "li_net_new_followers", views: "li_impressions", interactions: "li_interactions" },
} as const;
